#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
	configure)
		if [ -z "$2" ]; then
			echo "Updating system environment ..."
			pam-auth-update --force --package --remove ldap
		fi

		dpkg-trigger update-workbench

		echo "Updating configuration database ..."
		omv-confdbadm create "conf.service.ldap"
		if [ -n "$2" ]; then
			omv-confdbadm migrate "conf.service.ldap" "${2}"
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0
